version: '3.0'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  rails: &backend_base
    build: ./backend
    depends_on:
      - db
    environment:
      CORE_CONNECT_ENV: msndt-4
    ports:
      - "80:3000"
    volumes:
      - ./backend:/usr/src
    tty: true
    stdin_open: true